// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktdlcwwxoqraeeucumdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZGxjd3d4b3FyYWVldWN1bWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTg5NTEsImV4cCI6MjA2OTY5NDk1MX0.AKRr8Y3GpZPb96gmzN--mO05z0_6-HA_Sfs1V72xY28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});